### PR TITLE
Expect trailing comma's

### PR DESCRIPTION
**Pull request by suweller**

### CODE REVIEW

**Comment by andremedeiros** [comment]
I understand doing it on multiple lines, but why on the same line?

**Comment by suweller** [comment]
To keep consistent? :p
I'm fine with not doing it on a single line. That doesn't affect the commit size the way it does with multi line hashes and arrays

**Comment by aseyedmehdi** [comment]
still relevant @suweller ?

**Comment by suweller** [comment]
This whole repository can go as far as I'm concerned. We have .rubocop.yml in `revolution`, and can refer breaking of the styleguide by letting someone run `rubocop-git master` in their feature branch

**Pull request closed without merging**
